name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          pip install flask

      - name: Rodar testes (simulação de validação)
        run: |
          echo "Rodando testes..."
          python -m compileall .

      - name: Simular deploy
        run: |
          echo "Deploy realizado com sucesso 🚀"